### ISSUE TITLE
[Feat] 학습된 모델 테스트 및 MINIO 저장 관련 로직

### ISSUE THREAD

**Issue by Kguswo** [Kguswo/SCV#3]
[Feat] 학습된 모델 테스트 및 MINIO 저장 관련 로직

MINIO에 모델을 저장 및 모델로 테스트데이터 실행
## 구현 내용

- 모델 저장 시 스크립트화
- 테스트 데이터 실행 결과 반환 API

## To-Do

- MINIO 메서드 수정
- API 구현
- API 명세서 작성

## 수정할 사항
- [x] 모델ID와 버전ID를 조합해 유일한 모델파일이름 만들기
- [x] 실행 버튼을 누르면 
  - 모델 `json`
    - 블록뷰 `json`
    - 코드뷰 `string`
  - 데이터 셋 ( MNIST, Fashion-MNIST, CIFAR-10, CIFAR-100, …) `ENUM` ~~~~( RDB 에 컬럼으로)
  - Test Accuracy `float`
  - Test Loss `float`
  - Train epoch 당 Loss, Accuracy  `float[]` → chart.js
  - 해당되는 Layer 마다 Parameter 개수 (torch summary) `int[]`
만 반환, 저장버튼 누르면 나머지 포함해서 반환
- [x] 나머지 이상한 부분 찾아보고 수정

*Migrated from GitLab: https://lab.ssafy.com/s11-final/S11P31A107/-/issues/3*

**Comment by Kguswo** [comment]
mentioned in commit d0a379507b7ea824376ec9d852e67c2b334ce71c

**Comment by Kguswo** [comment]
mentioned in commit 097a6655d20f98f69f8b69294c38e244a46eee89

**Comment by Kguswo** [comment]
mentioned in commit 894e64f3ebb4efb69e10a89d2bcd9fd81a618b42

**Comment by Kguswo** [comment]
mentioned in commit c7b8619c824dded6d9897b2c9ea4318692933f3a

**Comment by Kguswo** [comment]
mentioned in commit 22d88832193d2dfd4a53d3a951459c3f8f1918ad

**Comment by Kguswo** [comment]
mentioned in commit c0cfe3f9419d8bc03874e48ca51bd543de596aef

**Comment by Kguswo** [comment]
marked the checklist item **나머지 이상한 부분 찾아보고 수정** as completed

**Comment by Kguswo** [comment]
marked the checklist item **실행 버튼을 누르면** as completed

**Comment by Kguswo** [comment]
marked the checklist item **모델ID와 버전ID를 조합해 유일한 모델파일이름 만들기** as completed

**Comment by Kguswo** [comment]
mentioned in commit 00b5218bd47014e23f1bfe57019ef26476fcd3c7
